/*
  Generated by generate_split_loops.py
  Objective B, Task T01: split j outer, order jo-i-p-ji
*/

#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>

#ifndef COMPUTE_NAME
#define COMPUTE_NAME tuned_t01_jip
#endif

void COMPUTE_NAME(int m0, int n0,
                  float *A_distributed,
                  float *B_distributed,
                  float *C_distributed)
{
    int rid;
    int num_ranks;
    int root_rid = 0;

    int rs_A = m0; int cs_A = 1;
    int rs_B = m0; int cs_B = 1;
    int rs_C = m0; int cs_C = 1;

    MPI_Comm_rank(MPI_COMM_WORLD, &rid);
    MPI_Comm_size(MPI_COMM_WORLD, &num_ranks);

    if (rid == root_rid) {
        // Initialize C for triangular region (j >= i)
        for (int j0 = 0; j0 < n0; ++j0) {
            for (int i0 = 0; i0 < (m0 < j0 + 1 ? m0 : j0 + 1); ++i0) {
                C_distributed[i0 * cs_C + j0 * rs_C] = 0.0f;
            }
        }

        const int BLOCK = 32;
        for (int jo = 0; jo < n0; jo += BLOCK) {
            int j_block_end = (jo + BLOCK < n0 ? jo + BLOCK : n0);
            for (int i0 = 0; i0 < (m0 < j_block_end ? m0 : j_block_end); ++i0) {
                for (int p0 = 0; p0 < m0; ++p0) {
                    int ji_start = (i0 > jo ? i0 - jo : 0);
                    for (int ji = ji_start; ji < j_block_end - jo; ++ji) {
                        int j0 = jo + ji;
                        C_distributed[i0 * cs_C + j0 * rs_C] +=
                            A_distributed[i0 * cs_A + p0 * rs_A] *
                            B_distributed[p0 * cs_B + j0 * rs_B];
                    }
                }
            }
        }

    }
}
