/*
  Generated by generate_split_loops.py
  Objective B, Task T01: split p outer, order po-i-j-pi
*/

#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>

#ifndef COMPUTE_NAME
#define COMPUTE_NAME tuned_t01_pij
#endif

void COMPUTE_NAME(int m0, int n0,
                  float *A_distributed,
                  float *B_distributed,
                  float *C_distributed)
{
    int rid;
    int num_ranks;
    int root_rid = 0;

    int rs_A = m0; int cs_A = 1;
    int rs_B = m0; int cs_B = 1;
    int rs_C = m0; int cs_C = 1;

    MPI_Comm_rank(MPI_COMM_WORLD, &rid);
    MPI_Comm_size(MPI_COMM_WORLD, &num_ranks);

    if (rid == root_rid) {
        // Initialize C for triangular region (j >= i)
        for (int j0 = 0; j0 < n0; ++j0) {
            for (int i0 = 0; i0 < (m0 < j0 + 1 ? m0 : j0 + 1); ++i0) {
                C_distributed[i0 * cs_C + j0 * rs_C] = 0.0f;
            }
        }

        const int BLOCK = 32;
        for (int po = 0; po < m0; po += BLOCK) {
            int p_block_end = (po + BLOCK < m0 ? po + BLOCK : m0);
            for (int i0 = 0; i0 < m0; ++i0) {
                for (int j0 = (i0 < n0 ? i0 : n0); j0 < n0; ++j0) {
                    for (int pi = po; pi < p_block_end; ++pi) {
                        C_distributed[i0 * cs_C + j0 * rs_C] +=
                            A_distributed[i0 * cs_A + pi * rs_A] *
                            B_distributed[pi * cs_B + j0 * rs_B];
                    }
                }
            }
        }

    }
}
