import os

BLOCK_SIZE = 32

auto_header = """/*
  Generated by generate_split_loops.py
  Objective B, Task T01: {description}
*/

#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>

#ifndef COMPUTE_NAME
#define COMPUTE_NAME {func_name}
#endif

void COMPUTE_NAME(int m0, int n0,
                  float *A_distributed,
                  float *B_distributed,
                  float *C_distributed)
{{
    int rid;
    int num_ranks;
    int root_rid = 0;

    int rs_A = m0; int cs_A = 1;
    int rs_B = m0; int cs_B = 1;
    int rs_C = m0; int cs_C = 1;

    MPI_Comm_rank(MPI_COMM_WORLD, &rid);
    MPI_Comm_size(MPI_COMM_WORLD, &num_ranks);

    if (rid == root_rid) {{
        // Initialize C for triangular region (j >= i)
        for (int j0 = 0; j0 < n0; ++j0) {{
            for (int i0 = 0; i0 < (m0 < j0 + 1 ? m0 : j0 + 1); ++i0) {{
                C_distributed[i0 * cs_C + j0 * rs_C] = 0.0f;
            }}
        }}

{body}
    }}
}}
"""


def body_ijp():
    return f"""        const int BLOCK = {BLOCK_SIZE};
        for (int io = 0; io < m0; io += BLOCK) {{
            int i_block_end = (io + BLOCK < m0 ? io + BLOCK : m0);
            for (int j0 = io; j0 < n0; ++j0) {{
                for (int p0 = 0; p0 < m0; ++p0) {{
                    int ii_limit = (i_block_end < j0 + 1 ? i_block_end : j0 + 1) - io;
                    for (int ii = 0; ii < ii_limit; ++ii) {{
                        int i0 = io + ii;
                        C_distributed[i0 * cs_C + j0 * rs_C] +=
                            A_distributed[i0 * cs_A + p0 * rs_A] *
                            B_distributed[p0 * cs_B + j0 * rs_B];
                    }}
                }}
            }}
        }}
"""


def body_jip():
    return f"""        const int BLOCK = {BLOCK_SIZE};
        for (int jo = 0; jo < n0; jo += BLOCK) {{
            int j_block_end = (jo + BLOCK < n0 ? jo + BLOCK : n0);
            for (int i0 = 0; i0 < (m0 < j_block_end ? m0 : j_block_end); ++i0) {{
                for (int p0 = 0; p0 < m0; ++p0) {{
                    int ji_start = (i0 > jo ? i0 - jo : 0);
                    for (int ji = ji_start; ji < j_block_end - jo; ++ji) {{
                        int j0 = jo + ji;
                        C_distributed[i0 * cs_C + j0 * rs_C] +=
                            A_distributed[i0 * cs_A + p0 * rs_A] *
                            B_distributed[p0 * cs_B + j0 * rs_B];
                    }}
                }}
            }}
        }}
"""


def body_ipj():
    return f"""        const int BLOCK = {BLOCK_SIZE};
        for (int io = 0; io < m0; io += BLOCK) {{
            int i_block_end = (io + BLOCK < m0 ? io + BLOCK : m0);
            for (int p0 = 0; p0 < m0; ++p0) {{
                for (int j0 = io; j0 < n0; ++j0) {{
                    int ii_limit = (i_block_end < j0 + 1 ? i_block_end : j0 + 1) - io;
                    for (int ii = 0; ii < ii_limit; ++ii) {{
                        int i0 = io + ii;
                        C_distributed[i0 * cs_C + j0 * rs_C] +=
                            A_distributed[i0 * cs_A + p0 * rs_A] *
                            B_distributed[p0 * cs_B + j0 * rs_B];
                    }}
                }}
            }}
        }}
"""


def body_pij():
    return f"""        const int BLOCK = {BLOCK_SIZE};
        for (int po = 0; po < m0; po += BLOCK) {{
            int p_block_end = (po + BLOCK < m0 ? po + BLOCK : m0);
            for (int i0 = 0; i0 < m0; ++i0) {{
                for (int j0 = (i0 < n0 ? i0 : n0); j0 < n0; ++j0) {{
                    for (int pi = po; pi < p_block_end; ++pi) {{
                        C_distributed[i0 * cs_C + j0 * rs_C] +=
                            A_distributed[i0 * cs_A + pi * rs_A] *
                            B_distributed[pi * cs_B + j0 * rs_B];
                    }}
                }}
            }}
        }}
"""


def body_jpi():
    return f"""        const int BLOCK = {BLOCK_SIZE};
        for (int jo = 0; jo < n0; jo += BLOCK) {{
            int j_block_end = (jo + BLOCK < n0 ? jo + BLOCK : n0);
            for (int p0 = 0; p0 < m0; ++p0) {{
                for (int i0 = 0; i0 < (m0 < j_block_end ? m0 : j_block_end); ++i0) {{
                    int ji_start = (i0 > jo ? i0 - jo : 0);
                    for (int ji = ji_start; ji < j_block_end - jo; ++ji) {{
                        int j0 = jo + ji;
                        C_distributed[i0 * cs_C + j0 * rs_C] +=
                            A_distributed[i0 * cs_A + p0 * rs_A] *
                            B_distributed[p0 * cs_B + j0 * rs_B];
                    }}
                }}
            }}
        }}
"""


def body_pji():
    return f"""        const int BLOCK = {BLOCK_SIZE};
        for (int po = 0; po < m0; po += BLOCK) {{
            int p_block_end = (po + BLOCK < m0 ? po + BLOCK : m0);
            for (int j0 = 0; j0 < n0; ++j0) {{
                int i_limit = (m0 < j0 + 1 ? m0 : j0 + 1);
                for (int i0 = 0; i0 < i_limit; ++i0) {{
                    for (int pi = po; pi < p_block_end; ++pi) {{
                        C_distributed[i0 * cs_C + j0 * rs_C] +=
                            A_distributed[i0 * cs_A + pi * rs_A] *
                            B_distributed[pi * cs_B + j0 * rs_B];
                    }}
                }}
            }}
        }}
"""


PERMUTATIONS = [
    ("ijp", "split i outer, order io-j-p-ii", body_ijp),
    ("jip", "split j outer, order jo-i-p-ji", body_jip),
    ("ipj", "split i outer, order io-p-j-ii", body_ipj),
    ("pij", "split p outer, order po-i-j-pi", body_pij),
    ("jpi", "split j outer, order jo-p-i-ji", body_jpi),
    ("pji", "split p outer, order po-j-i-pi", body_pji),
]


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    out_dir = os.path.join(script_dir, "../T01")
    os.makedirs(out_dir, exist_ok=True)

    for perm, description, body_fn in PERMUTATIONS:
        func_name = f"tuned_t01_{perm}"
        body = body_fn()
        content = auto_header.format(description=description, func_name=func_name, body=body)
        out_path = os.path.join(out_dir, f"obj_b_t01_{perm}.c")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Generated {out_path}")


if __name__ == "__main__":
    main()
