import os

# Definition of the six loop permutations
permutations = [
    "ijp", "jip", "ipj", "pij", "jpi", "pji"
]

# Template for the C file
c_template = """/*
  Generated by generate_loops.py
  Objective B, Task T00: {perm} loop ordering, if-condition eliminated.
*/

#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>

#ifndef COMPUTE_NAME
#define COMPUTE_NAME {func_name}
#endif

void COMPUTE_NAME(int m0, int n0,
                  float *A_distributed,
                  float *B_distributed,
                  float *C_distributed)
{{
    int rid;
    int num_ranks;
    int root_rid = 0;

    // Layout for matrices (Column Major)
    int rs_A = m0; int cs_A = 1;
    int rs_B = m0; int cs_B = 1;
    int rs_C = m0; int cs_C = 1;

    MPI_Comm_rank(MPI_COMM_WORLD, &rid);
    MPI_Comm_size(MPI_COMM_WORLD, &num_ranks);

    if (rid == root_rid) {{
        // Initialize C to 0 if necessary (required for non-innermost p loops)
        {init_code}
        
        // Loop Permutation: {perm}
        {loop_body}
    }}
}}
"""

def generate_loop_nest(perm):
    # Determine bounds based on j >= i condition
    # i: 0..m0
    # j: 0..n0
    # p: 0..m0
    # Constraint: j >= i  =>  i <= j
    
    # Map loop vars to their standard full ranges and stepping
    loops = {
        'i': {'var': 'i0', 'limit': 'm0', 'inc': '++i0'},
        'j': {'var': 'j0', 'limit': 'n0', 'inc': '++j0'},
        'p': {'var': 'p0', 'limit': 'm0', 'inc': '++p0'}
    }

    code = ""
    indent = "        "
    
    # Helper to construct loop header
    def make_for(v, start, end):
        return f"for (int {v} = {start}; {v} < {end}; ++{v})"

    # Construct the nested loops based on permutation order
    vars_ordered = list(perm) # e.g. ['i', 'j', 'p']
    
    # We need to adjust start/end based on previous loops to satisfy j >= i
    # Logic:
    # If 'i' is encountered:
    #   If 'j' was already seen (outer), 'i' goes from 0 to min(m0, j0 + 1)
    #   If 'j' is not seen yet (inner), 'i' goes from 0 to min(m0, n0) (conservative max)
    # If 'j' is encountered:
    #   If 'i' was already seen (outer), 'j' goes from i0 to n0
    #   If 'i' is not seen yet (inner), 'j' goes from 0 to n0 (but inner 'i' will be constrained)

    # Note: simple logic for 3 levels
    l1, l2, l3 = vars_ordered[0], vars_ordered[1], vars_ordered[2]
    
    # Determine bounds for L1
    start1, end1 = "0", loops[l1]['limit']
    if l1 == 'i':
        # i is outer. If j is inner, i must be valid start for j. i < n0 implied?
        # Safe to iterate i up to m0, inner j loop handles constraint.
        # But for tight bounds: i must be <= j < n0. So i < n0.
        end1 = f"({loops['i']['limit']} < {loops['j']['limit']} ? {loops['i']['limit']} : {loops['j']['limit']})"
    
    code += f"{indent}{make_for(loops[l1]['var'], start1, end1)}\n"
    code += f"{indent}{{\n"
    
    # Determine bounds for L2
    start2, end2 = "0", loops[l2]['limit']
    if l2 == 'i':
        # i is 2nd. 
        if l1 == 'j': end2 = f"({loops['j']['var']} + 1 < {loops['i']['limit']} ? {loops['j']['var']} + 1 : {loops['i']['limit']})" # i <= j
        elif l1 == 'p': end2 = f"({loops['i']['limit']} < {loops['j']['limit']} ? {loops['i']['limit']} : {loops['j']['limit']})" # i outer effectively
    if l2 == 'j':
        if l1 == 'i': start2 = loops['i']['var'] # j >= i
        
    code += f"{indent}  {make_for(loops[l2]['var'], start2, end2)}\n"
    code += f"{indent}  {{\n"

    # Determine bounds for L3
    start3, end3 = "0", loops[l3]['limit']
    if l3 == 'i':
        # i is inner. Constraint i <= j.
        # Find j in l1 or l2
        j_var = loops['j']['var']
        end3 = f"({j_var} + 1 < {loops['i']['limit']} ? {j_var} + 1 : {loops['i']['limit']})"
    if l3 == 'j':
        # j is inner. Constraint j >= i.
        # Find i in l1 or l2
        i_var = loops['i']['var']
        start3 = i_var

    code += f"{indent}    {make_for(loops[l3]['var'], start3, end3)}\n"
    code += f"{indent}    {{\n"
    
    # Inner body
    # Standard accumulation: C[i,j] += A[i,p] * B[p,j]
    # To optimize 'p' innermost, we use a scalar 'res'
    
    # Check if p is innermost
    if l3 == 'p':
        # Scalar replacement for C[i,j]
        # We need to know if C was initialized.
        # If p is innermost, we can do: float res = 0; for p... res += ...; C = res;
        # But strictly, the loop headers are generated above.
        # Let's use direct access for simplicity across all variants, 
        # relying on the init block outside.
        pass

    term = f"A_distributed[i0 * cs_A + p0 * rs_A] * B_distributed[p0 * cs_B + j0 * rs_B]"
    acc  = f"C_distributed[i0 * cs_C + j0 * rs_C] += {term};"
    
    # Optimization for P-innermost (ijp, jip): use scalar 'res'
    if perm in ['ijp', 'jip']:
        # This requires modifying the structure slightly (res decl before L3, writeback after L3)
        # We will handle this by returning a custom body for these 2 specific cases to match the 'baseline' performance style
        pass

    code += f"{indent}      {acc}\n"
    code += f"{indent}    }}\n"
    code += f"{indent}  }}\n"
    code += f"{indent}}}\n"

    return code

def generate_optimized_body(perm):
    # Specialized generators for specific orders to ensure high quality C code
    # Implements "Eliminate the innermost if" logic
    
    lines = []
    
    if perm == 'ijp':
        lines.append(f"for (int i0 = 0; i0 < (m0 < n0 ? m0 : n0); ++i0)")
        lines.append(f"{{")
        lines.append(f"  for (int j0 = i0; j0 < n0; ++j0)")
        lines.append(f"  {{")
        lines.append(f"    float res = 0.0f;")
        lines.append(f"    for (int p0 = 0; p0 < m0; ++p0)")
        lines.append(f"    {{")
        lines.append(f"      res += A_distributed[i0 * cs_A + p0 * rs_A] * B_distributed[p0 * cs_B + j0 * rs_B];")
        lines.append(f"    }}")
        lines.append(f"    C_distributed[i0 * cs_C + j0 * rs_C] = res;")
        lines.append(f"  }}")
        lines.append(f"}}")

    elif perm == 'jip':
        lines.append(f"for (int j0 = 0; j0 < n0; ++j0)")
        lines.append(f"{{")
        lines.append(f"  for (int i0 = 0; i0 < (m0 < j0 + 1 ? m0 : j0 + 1); ++i0)")
        lines.append(f"  {{")
        lines.append(f"    float res = 0.0f;")
        lines.append(f"    for (int p0 = 0; p0 < m0; ++p0)")
        lines.append(f"    {{")
        lines.append(f"      res += A_distributed[i0 * cs_A + p0 * rs_A] * B_distributed[p0 * cs_B + j0 * rs_B];")
        lines.append(f"    }}")
        lines.append(f"    C_distributed[i0 * cs_C + j0 * rs_C] = res;")
        lines.append(f"  }}")
        lines.append(f"}}")

    elif perm == 'ipj':
        lines.append(f"for (int i0 = 0; i0 < (m0 < n0 ? m0 : n0); ++i0)")
        lines.append(f"{{")
        lines.append(f"  for (int p0 = 0; p0 < m0; ++p0)")
        lines.append(f"  {{")
        lines.append(f"    float A_val = A_distributed[i0 * cs_A + p0 * rs_A];")
        lines.append(f"    for (int j0 = i0; j0 < n0; ++j0)")
        lines.append(f"    {{")
        lines.append(f"      C_distributed[i0 * cs_C + j0 * rs_C] += A_val * B_distributed[p0 * cs_B + j0 * rs_B];")
        lines.append(f"    }}")
        lines.append(f"  }}")
        lines.append(f"}}")

    elif perm == 'pij':
        lines.append(f"for (int p0 = 0; p0 < m0; ++p0)")
        lines.append(f"{{")
        lines.append(f"  for (int i0 = 0; i0 < (m0 < n0 ? m0 : n0); ++i0)")
        lines.append(f"  {{")
        lines.append(f"    float A_val = A_distributed[i0 * cs_A + p0 * rs_A];")
        lines.append(f"    for (int j0 = i0; j0 < n0; ++j0)")
        lines.append(f"    {{")
        lines.append(f"      C_distributed[i0 * cs_C + j0 * rs_C] += A_val * B_distributed[p0 * cs_B + j0 * rs_B];")
        lines.append(f"    }}")
        lines.append(f"  }}")
        lines.append(f"}}")

    elif perm == 'jpi':
        lines.append(f"for (int j0 = 0; j0 < n0; ++j0)")
        lines.append(f"{{")
        lines.append(f"  for (int p0 = 0; p0 < m0; ++p0)")
        lines.append(f"  {{")
        lines.append(f"    float B_val = B_distributed[p0 * cs_B + j0 * rs_B];")
        lines.append(f"    for (int i0 = 0; i0 < (m0 < j0 + 1 ? m0 : j0 + 1); ++i0)")
        lines.append(f"    {{")
        lines.append(f"      C_distributed[i0 * cs_C + j0 * rs_C] += B_val * A_distributed[i0 * cs_A + p0 * rs_A];")
        lines.append(f"    }}")
        lines.append(f"  }}")
        lines.append(f"}}")

    elif perm == 'pji':
        lines.append(f"for (int p0 = 0; p0 < m0; ++p0)")
        lines.append(f"{{")
        lines.append(f"  for (int j0 = 0; j0 < n0; ++j0)")
        lines.append(f"  {{")
        lines.append(f"    float B_val = B_distributed[p0 * cs_B + j0 * rs_B];")
        lines.append(f"    for (int i0 = 0; i0 < (m0 < j0 + 1 ? m0 : j0 + 1); ++i0)")
        lines.append(f"    {{")
        lines.append(f"      C_distributed[i0 * cs_C + j0 * rs_C] += B_val * A_distributed[i0 * cs_A + p0 * rs_A];")
        lines.append(f"    }}")
        lines.append(f"  }}")
        lines.append(f"}}")

    return "\n        ".join(lines)


# Main generation loop
for perm in permutations:
    filename = f"obj_b_t00_{perm}.c"
    func_name = f"tuned_{perm}"
    
    # For variants where 'p' is NOT innermost, we must initialize C to 0.
    # In 'ijp' and 'jip', C is overwritten by 'res', so implicit init is fine (or 'res=0').
    # For others, we accumulate (+=), so C must be 0-initialized first.
    init_code = ""
    if perm not in ['ijp', 'jip']:
        # Generate an initialization loop for C
        init_code = """
        for (int j0 = 0; j0 < n0; ++j0) {
            for (int i0 = 0; i0 < (m0 < j0 + 1 ? m0 : j0 + 1); ++i0) {
                 C_distributed[i0 * cs_C + j0 * rs_C] = 0.0f;
            }
        }
        """

    content = c_template.format(
        perm=perm,
        func_name=func_name,
        init_code=init_code,
        loop_body=generate_optimized_body(perm)
    )
    
    with open(filename, "w") as f:
        f.write(content)
    print(f"Generated {filename}")