import os
import textwrap

permutations = [
    "ijp", "jip", "ipj", "pij", "jpi", "pji",
]

c_template = textwrap.dedent(
    """
    /*
      Generated by generate_loops.py
      Objective B, Task T00: {perm} loop ordering, if-condition eliminated.
    */

    #include <mpi.h>
    #include <stdio.h>
    #include <stdlib.h>

    #ifndef COMPUTE_NAME
    #define COMPUTE_NAME {func_name}
    #endif

    void COMPUTE_NAME(int m0, int n0,
                      float *A_distributed,
                      float *B_distributed,
                      float *C_distributed)
    {{
        int rid;
        int num_ranks;
        const int root_rid = 0;

        /* Column-major layout */
        const int rs_A = m0; const int cs_A = 1;
        const int rs_B = m0; const int cs_B = 1;
        const int rs_C = m0; const int cs_C = 1;

        MPI_Comm_rank(MPI_COMM_WORLD, &rid);
        MPI_Comm_size(MPI_COMM_WORLD, &num_ranks);

        if (rid == root_rid)
        {{
{init_block}            /* Loop permutation: {perm} */
{loop_body}        }}
    }}
    """
)

bodies = {
    "ijp": textwrap.dedent(
        """
            for (int i0 = 0; i0 < (m0 < n0 ? m0 : n0); ++i0) {
                for (int j0 = i0; j0 < n0; ++j0) {
                    float res = 0.0f;
                    for (int p0 = 0; p0 < m0; ++p0) {
                        res += A_distributed[i0 * cs_A + p0 * rs_A] *
                               B_distributed[p0 * cs_B + j0 * rs_B];
                    }
                    C_distributed[i0 * cs_C + j0 * rs_C] = res;
                }
            }
        """
    ),
    "jip": textwrap.dedent(
        """
            for (int j0 = 0; j0 < n0; ++j0) {
                for (int i0 = 0; i0 < (m0 < j0 + 1 ? m0 : j0 + 1); ++i0) {
                    float res = 0.0f;
                    for (int p0 = 0; p0 < m0; ++p0) {
                        res += A_distributed[i0 * cs_A + p0 * rs_A] *
                               B_distributed[p0 * cs_B + j0 * rs_B];
                    }
                    C_distributed[i0 * cs_C + j0 * rs_C] = res;
                }
            }
        """
    ),
    "ipj": textwrap.dedent(
        """
            for (int i0 = 0; i0 < (m0 < n0 ? m0 : n0); ++i0) {
                for (int p0 = 0; p0 < m0; ++p0) {
                    const float A_val = A_distributed[i0 * cs_A + p0 * rs_A];
                    for (int j0 = i0; j0 < n0; ++j0) {
                        C_distributed[i0 * cs_C + j0 * rs_C] +=
                            A_val * B_distributed[p0 * cs_B + j0 * rs_B];
                    }
                }
            }
        """
    ),
    "pij": textwrap.dedent(
        """
            for (int p0 = 0; p0 < m0; ++p0) {
                for (int i0 = 0; i0 < (m0 < n0 ? m0 : n0); ++i0) {
                    const float A_val = A_distributed[i0 * cs_A + p0 * rs_A];
                    for (int j0 = i0; j0 < n0; ++j0) {
                        C_distributed[i0 * cs_C + j0 * rs_C] +=
                            A_val * B_distributed[p0 * cs_B + j0 * rs_B];
                    }
                }
            }
        """
    ),
    "jpi": textwrap.dedent(
        """
            for (int j0 = 0; j0 < n0; ++j0) {
                for (int p0 = 0; p0 < m0; ++p0) {
                    const float B_val = B_distributed[p0 * cs_B + j0 * rs_B];
                    for (int i0 = 0; i0 < (m0 < j0 + 1 ? m0 : j0 + 1); ++i0) {
                        C_distributed[i0 * cs_C + j0 * rs_C] +=
                            B_val * A_distributed[i0 * cs_A + p0 * rs_A];
                    }
                }
            }
        """
    ),
    "pji": textwrap.dedent(
        """
            for (int p0 = 0; p0 < m0; ++p0) {
                for (int j0 = 0; j0 < n0; ++j0) {
                    const float B_val = B_distributed[p0 * cs_B + j0 * rs_B];
                    for (int i0 = 0; i0 < (m0 < j0 + 1 ? m0 : j0 + 1); ++i0) {
                        C_distributed[i0 * cs_C + j0 * rs_C] +=
                            B_val * A_distributed[i0 * cs_A + p0 * rs_A];
                    }
                }
            }
        """
    ),
}

need_init = {"ipj", "pij", "jpi", "pji"}
base_dir = os.path.dirname(os.path.abspath(__file__))

for perm in permutations:
    init_block = ""
    if perm in need_init:
        init_block = textwrap.indent(
            textwrap.dedent(
                """
                for (int j0 = 0; j0 < n0; ++j0) {
                    for (int i0 = 0; i0 < (m0 < j0 + 1 ? m0 : j0 + 1); ++i0) {
                        C_distributed[i0 * cs_C + j0 * rs_C] = 0.0f;
                    }
                }

                """
            ),
            "        ",
        )

    content = c_template.format(
        perm=perm,
        func_name=f"tuned_{perm}",
        init_block=init_block,
        loop_body=textwrap.indent(bodies[perm].rstrip() + "\n", "        "),
    )

    out_path = os.path.join(base_dir, f"obj_b_t00_{perm}.c")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Generated {out_path}")
