
    /*
      Generated by generate_loops.py
      Objective B, Task T00: pij loop ordering, if-condition eliminated.
    */

    #include <mpi.h>
    #include <stdio.h>
    #include <stdlib.h>

    #ifndef COMPUTE_NAME
    #define COMPUTE_NAME tuned_pij
    #endif

    void COMPUTE_NAME(int m0, int n0,
                      float *A_distributed,
                      float *B_distributed,
                      float *C_distributed)
    {
        int rid;
        int num_ranks;
        const int root_rid = 0;

        /* Column-major layout */
        const int rs_A = m0; const int cs_A = 1;
        const int rs_B = m0; const int cs_B = 1;
        const int rs_C = m0; const int cs_C = 1;

        MPI_Comm_rank(MPI_COMM_WORLD, &rid);
        MPI_Comm_size(MPI_COMM_WORLD, &num_ranks);

        if (rid == root_rid)
        {

        for (int j0 = 0; j0 < n0; ++j0) {
            for (int i0 = 0; i0 < (m0 < j0 + 1 ? m0 : j0 + 1); ++i0) {
                C_distributed[i0 * cs_C + j0 * rs_C] = 0.0f;
            }
        }

            /* Loop permutation: pij */

        for (int p0 = 0; p0 < m0; ++p0) {
            for (int i0 = 0; i0 < (m0 < n0 ? m0 : n0); ++i0) {
                const float A_val = A_distributed[i0 * cs_A + p0 * rs_A];
                for (int j0 = i0; j0 < n0; ++j0) {
                    C_distributed[i0 * cs_C + j0 * rs_C] +=
                        A_val * B_distributed[p0 * cs_B + j0 * rs_B];
                }
            }
        }
        }
    }
